### ISSUE TITLE
Cassettes

### ISSUE THREAD

**Issue by sandelius** [buren/arbetsformedlingen#5]
Hey there. Do you have the cassettes available? The result changed so the tests fails atm.

**Comment by buren** [comment]
I do, however I have them locally right now. The idea being that the CI suite should use the live API in order to test it as close to "real life" as possible. That hasn't worked out very well, since ads are unpublished all the time, so I can't rely on any specific id and therefore data causing the test suite to fail, even though the code still works.

I'll update my cassettes locally and then publish them here, so we can have a reliable test suite :)

Again thanks you @sandelius 👍
